/**
 * Gaza Gateway — Initial Deterministic Booking Seeds
 *
 * Provides initial deterministic demo bookings for the canonical BookingRepository.
 * Kept completely isolated from CMS, staff, and analytics fixtures so ordinary
 * public startup does not bundle heavy static admin collections.
 */

import type { Booking } from "./booking.ts";
import type { Flight } from "../data.ts";

function makeSeedFlight(
  id: string,
  number: string,
  originCode: string,
  destinationCode: string,
  date: string,
  departTime: string,
  arriveTime: string,
  durationMinutes: number,
  aircraft: string,
  gate: string,
  basePrice: number,
): Flight {
  return {
    id,
    number,
    originCode,
    destinationCode,
    date,
    departTime,
    arriveTime,
    durationMinutes,
    aircraft,
    status: "Scheduled",
    gate,
    terminal: "1",
    basePrice,
    seatsLeft: 14,
  };
}

export const INITIAL_BOOKING_SEEDS: Booking[] = [
  {
    ref: "GZA4TQ",
    createdAt: "2026-08-30T10:12:00.000Z",
    criteria: {
      tripType: "round",
      origin: "GZA",
      destination: "AMM",
      departDate: "2026-09-19",
      returnDate: "2026-09-26",
      adults: 1,
      children: 1,
      infants: 0,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS100-2026-09-19-out",
      "PS100",
      "GZA",
      "AMM",
      "2026-09-19",
      "07:15",
      "08:10",
      55,
      "Airbus A320neo",
      "A1",
      129,
    ),
    inbound: makeSeedFlight(
      "PS101-2026-09-26-in",
      "PS101",
      "AMM",
      "GZA",
      "2026-09-26",
      "12:00",
      "12:55",
      55,
      "Airbus A320neo",
      "A1",
      129,
    ),
    fareId: "classic",
    passengers: [
      {
        id: "pax-GZA4TQ-0",
        type: "adult",
        firstName: "Nadia",
        lastName: "Sabbagh",
        dob: "1988-04-12",
        nationality: "Palestinian",
        document: "P GZA4TQ84213",
      },
      {
        id: "pax-GZA4TQ-1",
        type: "child",
        firstName: "Karim",
        lastName: "Sabbagh",
        dob: "2017-02-03",
        nationality: "Palestinian",
        document: "P GZA4TQ84214",
      },
    ],
    seats: {
      "out-0": "12A",
      "out-1": "12B",
      "in-0": "12A",
      "in-1": "12B",
    },
    extras: {
      pax: [
        { extraBags: 2, meal: "standard", assistance: [] },
        { extraBags: 0, meal: "child", assistance: [] },
      ],
    },
    contact: {
      email: "nadia.sabbagh@example.com",
      phone: "+970 59 000 1122",
    },
    total: 618,
    status: "confirmed",
    checkedIn: { out: [], in: [] },
    channel: "web",
    ownerEmail: "nadia.sabbagh@example.com",
  },
  {
    ref: "GZA9MK",
    createdAt: "2026-08-21T15:02:00.000Z",
    criteria: {
      tripType: "round",
      origin: "GZA",
      destination: "IST",
      departDate: "2026-09-18",
      returnDate: "2026-10-01",
      adults: 2,
      children: 0,
      infants: 1,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS106-2026-09-18-out",
      "PS106",
      "GZA",
      "IST",
      "2026-09-18",
      "10:40",
      "13:00",
      140,
      "Airbus A321neo",
      "A3",
      189,
    ),
    inbound: makeSeedFlight(
      "PS107-2026-10-01-in",
      "PS107",
      "IST",
      "GZA",
      "2026-10-01",
      "16:00",
      "18:20",
      140,
      "Airbus A321neo",
      "A3",
      189,
    ),
    fareId: "flex",
    passengers: [
      {
        id: "pax-GZA9MK-0",
        type: "adult",
        firstName: "Hisham",
        lastName: "Mansour",
        dob: "1979-11-02",
        nationality: "Palestinian",
        document: "P GZA9MK84213",
      },
      {
        id: "pax-GZA9MK-1",
        type: "adult",
        firstName: "Rasha",
        lastName: "Mansour",
        dob: "1983-06-19",
        nationality: "Palestinian",
        document: "P GZA9MK84214",
      },
      {
        id: "pax-GZA9MK-2",
        type: "infant",
        firstName: "Lina",
        lastName: "Mansour",
        dob: "2026-01-08",
        nationality: "Palestinian",
        document: "P LM10233",
        withAdult: 0,
      },
    ],
    seats: {
      "out-0": "8C",
      "out-1": "8D",
      "in-0": "8C",
      "in-1": "8D",
    },
    extras: {
      pax: [
        { extraBags: 2, meal: "standard", assistance: [] },
        { extraBags: 0, meal: "vegetarian", assistance: [] },
        { extraBags: 0, meal: "standard", assistance: [] },
      ],
    },
    contact: {
      email: "h.mansour@example.com",
      phone: "+970 59 000 3344",
    },
    total: 1284,
    status: "confirmed",
    checkedIn: { out: [0], in: [] },
    channel: "web",
    ownerEmail: null,
  },
  {
    ref: "GZA7RD",
    createdAt: "2026-09-01T08:00:00.000Z",
    criteria: {
      tripType: "oneway",
      origin: "GZA",
      destination: "DOH",
      departDate: "2026-09-17",
      returnDate: "",
      adults: 1,
      children: 0,
      infants: 0,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS108-2026-09-17-out",
      "PS108",
      "GZA",
      "DOH",
      "2026-09-17",
      "13:05",
      "16:15",
      190,
      "Boeing 737-800",
      "A2",
      249,
    ),
    inbound: null,
    fareId: "essential",
    passengers: [
      {
        id: "pax-GZA7RD-0",
        type: "adult",
        firstName: "Omar",
        lastName: "Halabi",
        dob: "1992-01-25",
        nationality: "Palestinian",
        document: "P GZA7RD84213",
      },
    ],
    seats: {
      "out-0": "5F",
    },
    extras: {
      pax: [{ extraBags: 0, meal: "standard", assistance: [] }],
    },
    contact: {
      email: "omar.halabi@example.com",
      phone: "+970 59 000 5566",
    },
    total: 296,
    status: "confirmed",
    checkedIn: { out: [0], in: [] },
    channel: "web",
    ownerEmail: "omar.halabi@example.com",
  },
  {
    ref: "GZA2BX",
    createdAt: "2026-09-10T12:22:00.000Z",
    criteria: {
      tripType: "round",
      origin: "GZA",
      destination: "CAI",
      departDate: "2026-10-04",
      returnDate: "2026-10-11",
      adults: 2,
      children: 2,
      infants: 0,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS102-2026-10-04-out",
      "PS102",
      "GZA",
      "CAI",
      "2026-10-04",
      "07:15",
      "08:30",
      75,
      "Airbus A320neo",
      "A4",
      139,
    ),
    inbound: makeSeedFlight(
      "PS103-2026-10-11-in",
      "PS103",
      "CAI",
      "GZA",
      "2026-10-11",
      "12:00",
      "13:15",
      75,
      "Airbus A320neo",
      "A4",
      139,
    ),
    fareId: "classic",
    passengers: [
      {
        id: "pax-GZA2BX-0",
        type: "adult",
        firstName: "Salma",
        lastName: "Rayyan",
        dob: "1985-03-30",
        nationality: "Palestinian",
        document: "P GZA2BX84213",
      },
      {
        id: "pax-GZA2BX-1",
        type: "adult",
        firstName: "Tareq",
        lastName: "Rayyan",
        dob: "1984-07-14",
        nationality: "Palestinian",
        document: "P GZA2BX84214",
      },
      {
        id: "pax-GZA2BX-2",
        type: "child",
        firstName: "Jana",
        lastName: "Rayyan",
        dob: "2015-09-09",
        nationality: "Palestinian",
        document: "P GZA2BX84215",
      },
      {
        id: "pax-GZA2BX-3",
        type: "child",
        firstName: "Adam",
        lastName: "Rayyan",
        dob: "2019-12-01",
        nationality: "Palestinian",
        document: "P GZA2BX84216",
      },
    ],
    seats: {
      "out-0": "14A",
      "out-1": "14B",
      "out-2": "14C",
      "out-3": "14D",
      "in-0": "14A",
      "in-1": "14B",
      "in-2": "14C",
      "in-3": "14D",
    },
    extras: {
      pax: [
        { extraBags: 1, meal: "standard", assistance: [] },
        { extraBags: 1, meal: "standard", assistance: [] },
        { extraBags: 0, meal: "child", assistance: [] },
        { extraBags: 0, meal: "child", assistance: [] },
      ],
    },
    contact: {
      email: "salma.rayyan@example.com",
      phone: "+970 59 000 7788",
    },
    total: 1096,
    status: "confirmed",
    checkedIn: { out: [], in: [] },
    channel: "web",
    ownerEmail: "salma.rayyan@example.com",
  },
  {
    ref: "GZA5ZN",
    createdAt: "2026-08-12T11:00:00.000Z",
    criteria: {
      tripType: "round",
      origin: "GZA",
      destination: "DXB",
      departDate: "2026-09-24",
      returnDate: "2026-09-30",
      adults: 2,
      children: 0,
      infants: 0,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS110-2026-09-24-out",
      "PS110",
      "GZA",
      "DXB",
      "2026-09-24",
      "16:20",
      "20:20",
      200,
      "Boeing 737-800",
      "A5",
      289,
    ),
    inbound: makeSeedFlight(
      "PS111-2026-09-30-in",
      "PS111",
      "DXB",
      "GZA",
      "2026-09-30",
      "21:00",
      "01:00",
      200,
      "Boeing 737-800",
      "A5",
      289,
    ),
    fareId: "flex",
    passengers: [
      {
        id: "pax-GZA5ZN-0",
        type: "adult",
        firstName: "Yara",
        lastName: "Dabbagh",
        dob: "1990-05-05",
        nationality: "Palestinian",
        document: "P GZA5ZN84213",
      },
      {
        id: "pax-GZA5ZN-1",
        type: "adult",
        firstName: "Fadi",
        lastName: "Dabbagh",
        dob: "1987-08-08",
        nationality: "Palestinian",
        document: "P GZA5ZN84214",
      },
    ],
    seats: {},
    extras: {
      pax: [
        { extraBags: 0, meal: "standard", assistance: [] },
        { extraBags: 0, meal: "standard", assistance: [] },
      ],
    },
    contact: {
      email: "yara.dabbagh@example.com",
      phone: "+970 59 000 9900",
    },
    total: 942,
    status: "cancelled",
    checkedIn: { out: [], in: [] },
    channel: "web",
    ownerEmail: null,
  },
  {
    ref: "GZA8LP",
    createdAt: "2026-09-04T19:05:00.000Z",
    criteria: {
      tripType: "round",
      origin: "GZA",
      destination: "JED",
      departDate: "2026-09-21",
      returnDate: "2026-09-28",
      adults: 2,
      children: 0,
      infants: 0,
      cabin: "economy",
    },
    outbound: makeSeedFlight(
      "PS112-2026-09-21-out",
      "PS112",
      "GZA",
      "JED",
      "2026-09-21",
      "10:40",
      "13:40",
      180,
      "Airbus A320neo",
      "A2",
      199,
    ),
    inbound: makeSeedFlight(
      "PS113-2026-09-28-in",
      "PS113",
      "JED",
      "GZA",
      "2026-09-28",
      "15:00",
      "18:00",
      180,
      "Airbus A320neo",
      "A2",
      199,
    ),
    fareId: "classic",
    passengers: [
      {
        id: "pax-GZA8LP-0",
        type: "adult",
        firstName: "Bashar",
        lastName: "Qudsi",
        dob: "1975-10-10",
        nationality: "Palestinian",
        document: "P GZA8LP84213",
      },
      {
        id: "pax-GZA8LP-1",
        type: "adult",
        firstName: "Hala",
        lastName: "Qudsi",
        dob: "1978-02-22",
        nationality: "Palestinian",
        document: "P GZA8LP84214",
      },
    ],
    seats: {
      "out-0": "9A",
      "out-1": "9B",
      "in-0": "9A",
      "in-1": "9B",
    },
    extras: {
      pax: [
        {
          extraBags: 1,
          meal: "standard",
          assistance: ["Wheelchair to the aircraft"],
        },
        { extraBags: 0, meal: "standard", assistance: [] },
      ],
    },
    contact: {
      email: "bashar.qudsi@example.com",
      phone: "+970 59 000 2211",
    },
    total: 704,
    status: "confirmed",
    checkedIn: { out: [], in: [] },
    channel: "web",
    ownerEmail: null,
  },
];
