/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AirportRouteImport } from './routes/airport'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBoardingPassesRouteImport } from './routes/account.boarding-passes'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountTravelersRouteImport } from './routes/account.travelers'
import { Route as AccountTripsRouteImport } from './routes/account.trips'
import { Route as AirportIndexRouteImport } from './routes/airport.index'
import { Route as AirportFutureRouteImport } from './routes/airport.future'
import { Route as AirportPastRouteImport } from './routes/airport.past'
import { Route as AirportPresentRouteImport } from './routes/airport.present'
import { Route as BookingConfirmationRefRouteImport } from './routes/booking-confirmation.$ref'
import { Route as DestinationsCodeRouteImport } from './routes/destinations.$code'
import { Route as FlightFlightIdRouteImport } from './routes/flight.$flightId'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageRefRouteImport } from './routes/manage.$ref'
import { Route as AccountTripsIndexRouteImport } from './routes/account.trips.index'
import { Route as AccountTripsRefRouteImport } from './routes/account.trips.$ref'
import { Route as BoardingPassRefPaxRouteImport } from './routes/boarding-pass.$ref.$pax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportRoute = AirportRouteImport.update({
  id: '/airport',
  path: '/airport',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBoardingPassesRoute = AccountBoardingPassesRouteImport.update({
  id: '/boarding-passes',
  path: '/boarding-passes',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTravelersRoute = AccountTravelersRouteImport.update({
  id: '/travelers',
  path: '/travelers',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTripsRoute = AccountTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AccountRoute,
} as any)
const AirportIndexRoute = AirportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AirportRoute,
} as any)
const AirportFutureRoute = AirportFutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => AirportRoute,
} as any)
const AirportPastRoute = AirportPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => AirportRoute,
} as any)
const AirportPresentRoute = AirportPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => AirportRoute,
} as any)
const BookingConfirmationRefRoute = BookingConfirmationRefRouteImport.update({
  id: '/booking-confirmation/$ref',
  path: '/booking-confirmation/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCodeRoute = DestinationsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DestinationsRoute,
} as any)
const FlightFlightIdRoute = FlightFlightIdRouteImport.update({
  id: '/flight/$flightId',
  path: '/flight/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRefRoute = ManageRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => ManageRoute,
} as any)
const AccountTripsIndexRoute = AccountTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountTripsRoute,
} as any)
const AccountTripsRefRoute = AccountTripsRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => AccountTripsRoute,
} as any)
const BoardingPassRefPaxRoute = BoardingPassRefPaxRouteImport.update({
  id: '/boarding-pass/$ref/$pax',
  path: '/boarding-pass/$ref/$pax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account': typeof AccountRouteWithChildren
  '/airport': typeof AirportRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/manage': typeof ManageRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/boarding-passes': typeof AccountBoardingPassesRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/travelers': typeof AccountTravelersRoute
  '/account/trips': typeof AccountTripsRouteWithChildren
  '/airport/future': typeof AirportFutureRoute
  '/airport/past': typeof AirportPastRoute
  '/airport/present': typeof AirportPresentRoute
  '/booking-confirmation/$ref': typeof BookingConfirmationRefRoute
  '/destinations/$code': typeof DestinationsCodeRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
  '/manage/$ref': typeof ManageRefRoute
  '/account/': typeof AccountIndexRoute
  '/airport/': typeof AirportIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/account/trips/$ref': typeof AccountTripsRefRoute
  '/boarding-pass/$ref/$pax': typeof BoardingPassRefPaxRoute
  '/account/trips/': typeof AccountTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/boarding-passes': typeof AccountBoardingPassesRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/travelers': typeof AccountTravelersRoute
  '/airport/future': typeof AirportFutureRoute
  '/airport/past': typeof AirportPastRoute
  '/airport/present': typeof AirportPresentRoute
  '/booking-confirmation/$ref': typeof BookingConfirmationRefRoute
  '/destinations/$code': typeof DestinationsCodeRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
  '/manage/$ref': typeof ManageRefRoute
  '/account': typeof AccountIndexRoute
  '/airport': typeof AirportIndexRoute
  '/manage': typeof ManageIndexRoute
  '/account/trips/$ref': typeof AccountTripsRefRoute
  '/boarding-pass/$ref/$pax': typeof BoardingPassRefPaxRoute
  '/account/trips': typeof AccountTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account': typeof AccountRouteWithChildren
  '/airport': typeof AirportRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/manage': typeof ManageRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/boarding-passes': typeof AccountBoardingPassesRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/travelers': typeof AccountTravelersRoute
  '/account/trips': typeof AccountTripsRouteWithChildren
  '/airport/future': typeof AirportFutureRoute
  '/airport/past': typeof AirportPastRoute
  '/airport/present': typeof AirportPresentRoute
  '/booking-confirmation/$ref': typeof BookingConfirmationRefRoute
  '/destinations/$code': typeof DestinationsCodeRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
  '/manage/$ref': typeof ManageRefRoute
  '/account/': typeof AccountIndexRoute
  '/airport/': typeof AirportIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/account/trips/$ref': typeof AccountTripsRefRoute
  '/boarding-pass/$ref/$pax': typeof BoardingPassRefPaxRoute
  '/account/trips/': typeof AccountTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access-denied'
    | '/account'
    | '/airport'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/manage'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/terms'
    | '/travel'
    | '/verify-email'
    | '/account/boarding-passes'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/account/travelers'
    | '/account/trips'
    | '/airport/future'
    | '/airport/past'
    | '/airport/present'
    | '/booking-confirmation/$ref'
    | '/destinations/$code'
    | '/flight/$flightId'
    | '/manage/$ref'
    | '/account/'
    | '/airport/'
    | '/manage/'
    | '/account/trips/$ref'
    | '/boarding-pass/$ref/$pax'
    | '/account/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access-denied'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/terms'
    | '/travel'
    | '/verify-email'
    | '/account/boarding-passes'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/account/travelers'
    | '/airport/future'
    | '/airport/past'
    | '/airport/present'
    | '/booking-confirmation/$ref'
    | '/destinations/$code'
    | '/flight/$flightId'
    | '/manage/$ref'
    | '/account'
    | '/airport'
    | '/manage'
    | '/account/trips/$ref'
    | '/boarding-pass/$ref/$pax'
    | '/account/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access-denied'
    | '/account'
    | '/airport'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/manage'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/terms'
    | '/travel'
    | '/verify-email'
    | '/account/boarding-passes'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/account/travelers'
    | '/account/trips'
    | '/airport/future'
    | '/airport/past'
    | '/airport/present'
    | '/booking-confirmation/$ref'
    | '/destinations/$code'
    | '/flight/$flightId'
    | '/manage/$ref'
    | '/account/'
    | '/airport/'
    | '/manage/'
    | '/account/trips/$ref'
    | '/boarding-pass/$ref/$pax'
    | '/account/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AccountRoute: typeof AccountRouteWithChildren
  AirportRoute: typeof AirportRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FlightsRoute: typeof FlightsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  ManageRoute: typeof ManageRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  TravelRoute: typeof TravelRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BookingConfirmationRefRoute: typeof BookingConfirmationRefRoute
  FlightFlightIdRoute: typeof FlightFlightIdRoute
  BoardingPassRefPaxRoute: typeof BoardingPassRefPaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport': {
      id: '/airport'
      path: '/airport'
      fullPath: '/airport'
      preLoaderRoute: typeof AirportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/boarding-passes': {
      id: '/account/boarding-passes'
      path: '/boarding-passes'
      fullPath: '/account/boarding-passes'
      preLoaderRoute: typeof AccountBoardingPassesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/travelers': {
      id: '/account/travelers'
      path: '/travelers'
      fullPath: '/account/travelers'
      preLoaderRoute: typeof AccountTravelersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/trips': {
      id: '/account/trips'
      path: '/trips'
      fullPath: '/account/trips'
      preLoaderRoute: typeof AccountTripsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/airport/': {
      id: '/airport/'
      path: '/'
      fullPath: '/airport/'
      preLoaderRoute: typeof AirportIndexRouteImport
      parentRoute: typeof AirportRoute
    }
    '/airport/future': {
      id: '/airport/future'
      path: '/future'
      fullPath: '/airport/future'
      preLoaderRoute: typeof AirportFutureRouteImport
      parentRoute: typeof AirportRoute
    }
    '/airport/past': {
      id: '/airport/past'
      path: '/past'
      fullPath: '/airport/past'
      preLoaderRoute: typeof AirportPastRouteImport
      parentRoute: typeof AirportRoute
    }
    '/airport/present': {
      id: '/airport/present'
      path: '/present'
      fullPath: '/airport/present'
      preLoaderRoute: typeof AirportPresentRouteImport
      parentRoute: typeof AirportRoute
    }
    '/booking-confirmation/$ref': {
      id: '/booking-confirmation/$ref'
      path: '/booking-confirmation/$ref'
      fullPath: '/booking-confirmation/$ref'
      preLoaderRoute: typeof BookingConfirmationRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$code': {
      id: '/destinations/$code'
      path: '/$code'
      fullPath: '/destinations/$code'
      preLoaderRoute: typeof DestinationsCodeRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/flight/$flightId': {
      id: '/flight/$flightId'
      path: '/flight/$flightId'
      fullPath: '/flight/$flightId'
      preLoaderRoute: typeof FlightFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/$ref': {
      id: '/manage/$ref'
      path: '/$ref'
      fullPath: '/manage/$ref'
      preLoaderRoute: typeof ManageRefRouteImport
      parentRoute: typeof ManageRoute
    }
    '/account/trips/': {
      id: '/account/trips/'
      path: '/'
      fullPath: '/account/trips/'
      preLoaderRoute: typeof AccountTripsIndexRouteImport
      parentRoute: typeof AccountTripsRoute
    }
    '/account/trips/$ref': {
      id: '/account/trips/$ref'
      path: '/$ref'
      fullPath: '/account/trips/$ref'
      preLoaderRoute: typeof AccountTripsRefRouteImport
      parentRoute: typeof AccountTripsRoute
    }
    '/boarding-pass/$ref/$pax': {
      id: '/boarding-pass/$ref/$pax'
      path: '/boarding-pass/$ref/$pax'
      fullPath: '/boarding-pass/$ref/$pax'
      preLoaderRoute: typeof BoardingPassRefPaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountTripsRouteChildren {
  AccountTripsRefRoute: typeof AccountTripsRefRoute
  AccountTripsIndexRoute: typeof AccountTripsIndexRoute
}

const AccountTripsRouteChildren: AccountTripsRouteChildren = {
  AccountTripsRefRoute: AccountTripsRefRoute,
  AccountTripsIndexRoute: AccountTripsIndexRoute,
}

const AccountTripsRouteWithChildren = AccountTripsRoute._addFileChildren(
  AccountTripsRouteChildren,
)

interface AccountRouteChildren {
  AccountBoardingPassesRoute: typeof AccountBoardingPassesRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountTravelersRoute: typeof AccountTravelersRoute
  AccountTripsRoute: typeof AccountTripsRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBoardingPassesRoute: AccountBoardingPassesRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountTravelersRoute: AccountTravelersRoute,
  AccountTripsRoute: AccountTripsRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AirportRouteChildren {
  AirportFutureRoute: typeof AirportFutureRoute
  AirportPastRoute: typeof AirportPastRoute
  AirportPresentRoute: typeof AirportPresentRoute
  AirportIndexRoute: typeof AirportIndexRoute
}

const AirportRouteChildren: AirportRouteChildren = {
  AirportFutureRoute: AirportFutureRoute,
  AirportPastRoute: AirportPastRoute,
  AirportPresentRoute: AirportPresentRoute,
  AirportIndexRoute: AirportIndexRoute,
}

const AirportRouteWithChildren =
  AirportRoute._addFileChildren(AirportRouteChildren)

interface DestinationsRouteChildren {
  DestinationsCodeRoute: typeof DestinationsCodeRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsCodeRoute: DestinationsCodeRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface ManageRouteChildren {
  ManageRefRoute: typeof ManageRefRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageRefRoute: ManageRefRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AccountRoute: AccountRouteWithChildren,
  AirportRoute: AirportRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FlightsRoute: FlightsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  ManageRoute: ManageRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  TravelRoute: TravelRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BookingConfirmationRefRoute: BookingConfirmationRefRoute,
  FlightFlightIdRoute: FlightFlightIdRoute,
  BoardingPassRefPaxRoute: BoardingPassRefPaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
