/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as DestinationsCodeRouteImport } from './routes/destinations.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCodeRoute = DestinationsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DestinationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/destinations/$code': typeof DestinationsCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/destinations/$code': typeof DestinationsCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/destinations/$code': typeof DestinationsCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/destinations' | '/flights' | '/destinations/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/destinations' | '/flights' | '/destinations/$code'
  id: '__root__' | '/' | '/destinations' | '/flights' | '/destinations/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FlightsRoute: typeof FlightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$code': {
      id: '/destinations/$code'
      path: '/$code'
      fullPath: '/destinations/$code'
      preLoaderRoute: typeof DestinationsCodeRouteImport
      parentRoute: typeof DestinationsRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsCodeRoute: typeof DestinationsCodeRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsCodeRoute: DestinationsCodeRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FlightsRoute: FlightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
